declare function require(name: string);

const articles = [
    require('../articles/0').default,
    require('../articles/1').default,
    require('../articles/2').default,
    require('../articles/3').default,
    require('../articles/4').default,
    require('../articles/5').default,
    require('../articles/6').default,
    require('../articles/7').default,
    require('../articles/8').default,
    require('../articles/9').default,
    require('../articles/10').default,
    require('../articles/11').default,
    require('../articles/12').default,
    require('../articles/13').default,
    require('../articles/14').default,
    require('../articles/15').default,
    require('../articles/16').default,
    require('../articles/17').default,
    require('../articles/18').default,
    require('../articles/19').default,
    require('../articles/20').default,
    require('../articles/21').default,
    require('../articles/22').default,
    require('../articles/23').default,
    require('../articles/24').default,
    require('../articles/25').default,
    require('../articles/26').default,
    require('../articles/27').default,
    require('../articles/28').default,
    require('../articles/29').default,
    require('../articles/30').default,
    require('../articles/31').default,
    require('../articles/32').default,
    require('../articles/33').default,
    require('../articles/34').default,
    require('../articles/35').default,
    require('../articles/36').default,
    require('../articles/37').default,
    require('../articles/38').default,
    require('../articles/39').default,
    require('../articles/40').default,
    require('../articles/41').default,
    require('../articles/42').default,
];

export default articles;
